version: '3.8'
services:
  web:
    build:
      context: .
      target: debug
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000
      - 2345:2345
    volumes:
      - .:/usr/src/app
    security_opt:
      - "seccomp:unconfined"
    command: /bin/sh -c "while sleep 1000; do :; done" #go run main.go
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: